# docker-compose.yml
version: '3.8' # Você pode remover esta linha para silenciar o aviso, como o Docker sugeriu.

services:
  postgres:
    image: postgres:16-alpine
    container_name: webhook-inspector-db

    ports:
      - "5433:5432" # <-- MUDANÇA CRÍTICA AQUI. "MáquinaLocal:DentroDoContêiner"

    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: webhooks

    volumes:
      - ./pgdata:/var/lib/postgresql/data

    restart: always